version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    target-branch: dependabot-updates

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    target-branch: dependabot-updates

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
