version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    target-branch: dependabot-updates
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    target-branch: dependabot-updates
    pull-request-branch-name:
      separator: "-"
