name: Dependabot PR Manager

on: 
 push:
    branches: [main]
 pull_request:
   branches: [main]
 workflow_dispatch:

jobs:
  dependabot:
    permissions: 
      pull-requests: read
    uses: eamonnk418/dependabot-pr-manager-action/.github/workflows/reusable-workflow.yml@main
    secrets: 
      github-token: ${{ secrets.GITHUB_TOKEN }}
