name: Dependabot PR Manager

on:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main
  workflow_dispatch: 

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependabot PR Manager
        uses: eamonnk418/dependabot-pr-manager-action@v1.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
