name: Dependabot PR Manager

on: 
 push:
    branches: [main]
 pull_request:
   branches: [main]
 workflow_dispatch:

jobs:
  dependabot:
    uses: eamonnk418/dependabot-pr-manager-action/.github/workflows/reusable-workflow.yml@main
    secrets: inherit
