name: Dependabot PR Manager

on: pull_request

jobs:
  dependabot:
    uses: eamonnk418/dependabot-pr-manager-action/.github/workflows/reusable-workflow.yml@main
    permissions: 
      pull-requests: read
    secrets: 
      github-token: ${{ secrets.GITHUB_TOKEN }}
