name: Dependabot PR Manager

on: pull_request 

jobs:
  dependabot:
    uses: eamonnk418/dependabot-pr-manager-action/.github/workflows/dependabot-pr-manager.yml@main
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}  
